services:
  - type: web
    name: subminder-frontend
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/sub-minder-app/browser
    envVars:
      - key: SUPABASE_URL
        value: https://your-project.supabase.co
      - key: SUPABASE_ANON_KEY
        value: your-anon-key
      - key: RESEND_API_KEY
        value: re_...
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 